services:
  api:
    container_name: mpit.server
    image: mpit
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      #- ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      #- ASPNETCORE_HTTPS_PORTS=8081
    build:
      context: .
      dockerfile: ./Dockerfile
    #volumes:
    #- ./ssl:/app/ssl
    #- ./:/app # delete on prod
    networks:
      - mpit
    depends_on:
      - user_db

  user_db:
    container_name: mpit.db
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mpit
      POSTGRES_USER: mpit2025
      POSTGRES_PASSWORD: mpit2025
    networks:
      - mpit
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  mpit:
    driver: bridge

volumes:
  postgres-data:
